import 'custom_item_store_and_wishlist_model.dart';

//Items Store List
List<DetailsItemStoreAndWishList> itemsStoreList = [
  DetailsItemStoreAndWishList(
      1,
      'assets/images/The Heart of Hell.png',
      'The Heart of Hell',
      'Mitch Weiss',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      true),
  DetailsItemStoreAndWishList(
      2,
      'assets/images/Adrennes 1944.png',
      'Adrennes 1944',
      'Antony Beevor',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      '#1 international bestseller and award\nwinning history book.',
      true),
  DetailsItemStoreAndWishList(
      3,
      'assets/images/War on the Gothic Line.png',
      'War on the Gothic Line',
      'Christian Jennings',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'assets/icons/StarOff.svg',
      'Through the eyes of thirteen men\nand women from seven different nations',
      true),
  DetailsItemStoreAndWishList(
      4,
      'assets/images/Tattletale.png',
      'Tattletale',
      'Sarah J. Noughton',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      true),
  DetailsItemStoreAndWishList(
      5,
      'assets/images/Red Queen.png',
      'Red Queen',
      'Rebecca Mackenzie',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      true),
];

// Items WishList

List<DetailsItemStoreAndWishList> itemsWishList = [
  DetailsItemStoreAndWishList(
      1,
      'assets/images/In A Land Of Paper Gods.png',
      'In A Land Of Paper\nGods',
      'Rebecca Mackenzie',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      false),
  DetailsItemStoreAndWishList(
      2,
      'assets/images/Willlows Of Fate.png',
      'Willlows Of Fate',
      'Sarah J. Noughton',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      false),
  DetailsItemStoreAndWishList(
      3,
      'assets/images/Red Queen.png',
      'Red Queen',
      'Rebecca Mackenzie',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'The untold story of courage and sacrifice\nin the shadow of Iwo Jima.',
      false),
  DetailsItemStoreAndWishList(
      4,
      'assets/images/Adrennes 1944.png',
      'Adrennes 1944',
      'Antony Beevor',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      '#1 international bestseller and award\nwinning history book.',
      false),
  DetailsItemStoreAndWishList(
      5,
      'assets/images/War on the Gothic Line.png',
      'War on the Gothic Line',
      'Christian Jennings',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOn.svg',
      'assets/icons/StarOff.svg',
      'assets/icons/StarOff.svg',
      'Through the eyes of thirteen men and\nwomen from seven different nations',
      false),
];
